server:
  port: 9100
  tomcat:
    max-connections: 8192
    max-http-form-post-size: 10MB
    max-swallow-size: 1GB
spring:
  application:
    name: ai-interviewer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_interviewer?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      # 最小空闲连接数 5
      minimum-idle: 5
      # 最大连接池 20
      maximum-pool-size: 20
      # 空闲超时 5 分钟
      idle-timeout: 300000
      # 连接池名称
      pool-name: HikariCP-AIInterviewer
      # 连接最大生命周期 30 分钟
      max-lifetime: 1800000
      # 连接超时 30 秒
      connection-timeout: 30000
      # 连接测试查询
      connection-test-query: select 1
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 1GB
